name: build_it
version: 0.2.9
description: The `build_it`is a builder that makes publicly available third-party source code generators and runs them during the build process for rapid development.
homepage: https://github.com/mezoni/build_it
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  analyzer: ^1.2.0
  build: ^2.0.0
  build_runner: ^1.12.2
  code_builder: ^3.7.0
  collection: ^1.15.0
  dart_style: ^2.0.0
  json_helpers: ^0.1.5
  json_serializable: ^4.1.0
  json_annotation: ^4.0.1
  meta: ^1.3.0
  path: ^1.8.0
  yaml: ^3.1.0
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
